// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package goservice

import (
	"database/sql"
)

type Employee struct {
	ID        int64
	Name      string
	Manager   sql.NullString
	StartDate sql.NullString
}
